export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/*BEGIN FETCH */
export const FETCH_GET = "FETCH_GET";

export const FETCH_IMAGE = "FETCH_IMAGE";

export const FETCH_IMAGE_USER_PROFILE = "FETCH_IMAGE_USER_PROFILE";

export const FETCH_SHOW_LIMIT = "FETCH_SHOW_LIMIT";

export const FETCH_MODAL_SHOW = "FETCH_MODAL_SHOW";

export const FETCH_POST_MODAL_SHOW = "FETCH_POST_MODAL_SHOW";

export const FETCH_MODAL_DATA = "FETCH_MODAL_DATA";

export const FETCH_POST_MODAL_SHOW_IMAGE = "FETCH_POST_MODAL_SHOW_IMAGE";

export const FETCH_MODAL_ERROR = "FETCH_MODAL_ERROR";

export const FETCH_MODAL_IMAGE = "FETCH_MODAL_IMAGE";

/*BEGIN FETCH COMMENT*/
export const FETCH_MODAL_COMMENT = "FETCH_MODAL_COMMENT";
/*END FETCH COMMENT*/

export const FETCH_MODAL_EMOTION = "FETCH_MODAL_EMOTION";

/*BEGIN FETCH COMMENT*/
export const FETCH_ITEM_MODAL_COMMENT = "FETCH_ITEM_MODAL_COMMENT";
/*END FETCH COMMENT*/

export const FETCH_ITEM_MODAL_EMOTION = "FETCH_ITEM_MODAL_EMOTION";

export const FETCH_LIST_COMMENTED_SHOW = "FETCH_LIST_COMMENTED_SHOW";

/*END FETCH */

/*BEGIN PROFILE*/
export const PROFILE_GET = "PROFILE_GET";

export const PROFILE_IMAGE = "PROFILE_IMAGE";

export const PROFILE_MODE_EDIT = "PROFILE_MODE_EDIT";

export const PROFILE_FROM_ERROR = "PROFILE_FROM_ERROR";

/*END PROFILE*/

/*BEGIN PERSONAL_FETCH*/
export const PERSONAL_FETCH_USER = "PERSONAL_FETCH_USER";

export const PERSONAL_FETCH_GET = "PERSONAL_FETCH_GET";

export const PERSONAL_FETCH_MODAL_IMAGE = "PERSONAL_FETCH_MODAL_IMAGE";

export const PERSONAL_FETCH_MODAL_ERROR = "PERSONAL_FETCH_MODAL_ERROR";

export const PERSONAL_FETCH_MODAL_COMMENT = "PERSONAL_FETCH_MODAL_COMMENT";

export const PERSONAL_FETCH_ITEM_MODAL_COMMENT =
  "PERSONAL_FETCH_ITEM_MODAL_COMMENT";

export const PERSONAL_FETCH_MODAL_EMOTION = "PERSONAL_FETCH_MODAL_EMOTION";

export const PERSONAL_FETCH_ITEM_MODAL_EMOTION =
  "PERSONAL_FETCH_ITEM_MODAL_EMOTION";

export const PERSONAL_FETCH_IMAGE = "PERSONAL_FETCH_IMAGE";

export const PERSONAL_FETCH_IMAGE_USER_PROFILE =
  "PERSONAL_FETCH_IMAGE_USER_PROFILE";

export const PERSONAL_FETCH_SHOW_LIMIT = "PERSONAL_FETCH_SHOW_LIMIT";

export const PERSONAL_FETCH_MODAL_SHOW = "PERSONAL_FETCH_MODAL_SHOW";

export const PERSONAL_FETCH_MODAL_DATA = "PERSONAL_FETCH_MODAL_DATA";

export const PERSONAL_FETCH_POST_MODAL_SHOW = "PERSONAL_FETCH_POST_MODAL_SHOW";

export const PERSONAL_FETCH_POST_MODAL_SHOW_IMAGE =
  "PERSONAL_FETCH_POST_MODAL_SHOW_IMAGE";

export const PERSONAL_FETCH_LIST_COMMENTED_SHOW =
  "PERSONAL_FETCH_LIST_COMMENTED_SHOW";

/*END PERSONAL_FETCH*/
